import { Link } from "@tanstack/react-router";
import {
	ArrowBigUp,
	ArrowUpRight,
	Bookmark,
	Check,
	Copy,
	MessageSquare,
} from "lucide-react";
import { useRef, useState } from "react";
import type { GetSkillsData } from "#/dataconnect-generated";

// Step 4: Define the props for the SkillCard component generated by Firebase
type SkillCardProps = GetSkillsData["skills"][number];

export const SkillCard = (skill: SkillCardProps) => {
	const [copied, setCopied] = useState(false);
	const resetTimeoutRef = useRef<number | null>(null);

	const handleCopy = async () => {
		if (!skill.installCommand) return;

		await navigator.clipboard.writeText(skill.installCommand);
		setCopied(true);

		if (resetTimeoutRef.current) {
			window.clearTimeout(resetTimeoutRef.current);
		}

		resetTimeoutRef.current = window.setTimeout(() => {
			setCopied(false);
		}, 1500);
	};

	return (
		<article className="skill-card">
			<Link
				className="overlay "
				to="/skills/$skillId"
				tabIndex={-1}
				aria-label={`Open ${skill.title}`}
			>
				{" "}
			</Link>

			<div className="chrome">
				<div className="chrome-bar">
					<div className="lights">
						<div className="light red"></div>
						<div className="light amber"></div>
						<div className="light green"></div>
					</div>
					<div className="host">registry.sh </div>
				</div>
			</div>
			<div className="body">
				<div className="meta">
					<div className="author">
						<img
							src={skill.author.imageUrl || "/logo512.png"}
							alt="author avatar"
							className="avatar"
						/>
						<div className="author-copy">
							<p>{skill.author.username}</p>
							<p>{new Date(skill.createdAt as string).toLocaleDateString()}</p>
						</div>
					</div>
					<p className="category">{skill.tags[0] ?? "General"}</p>
				</div>
				<div className="summary">
					<Link
						className="title-link"
						to="/skills/$skillId"
						params={{ skillId: skill.id }}
					>
						<h3>{skill.title}</h3>
					</Link>
					<p>{skill.description}</p>
				</div>
				<div className="command">
					<div className="command-copy">
						<span>{">_"}</span>
						<p>{skill.installCommand}</p>
					</div>
					<button
						type="button"
						className="copy"
						onClick={handleCopy}
						aria-label={`Copy install command for ${skill.title}`}
					>
						{copied ? <Check size={16} /> : <Copy size={16} />}
					</button>
				</div>
				<div className="footer">
					<div className="stats">
						<button type="button" className="upvote" disabled>
							<ArrowBigUp size={16} fill="currentColor" />
							<span>{skill.tags.length}</span>
						</button>

						<div className="comments">
							<MessageSquare size={14} />
							<span>{skill.author.email ? 1 : 0}</span>
						</div>
					</div>
					<div className="actions">
						<Link to="/skills" className="open" title={`Open ${skill.title}`}>
							<span>Open</span>
							<ArrowUpRight size={14} />
						</Link>
						<button
							type="button"
							className="save"
							aria-label="saved state"
							disabled
						>
							<Bookmark size={16} />
						</button>
					</div>
				</div>
			</div>
		</article>
	);
};
