# Step 1 - Define Query

query GetSkills($searchTerm: String = "", $limit: Int = 10, $offset: Int = 0)
@auth(level: PUBLIC, insecureReason: "Skills should be visible to everyone") {
  skills(
    where: {
      _or: [
        { title: { contains: $searchTerm } }
        { description: { contains: $searchTerm } }
      ]
    }
    orderBy: [{ createdAt: DESC }]
    limit: $limit
    offset: $offset
  ) {
    id
    title
    description
    tags
    createdAt
    installCommand
    author {
      username
      email
      imageUrl
      clerkId
    }
  }
}

query GetSkillById($id: UUID!)
@auth(level: PUBLIC, insecureReason: "Skills should be visible to everyone") {
  skill(id: $id) {
    id
    title
    description
    tags
    createdAt
    installCommand
    promptConfig
    usageExample
    author {
      username
      email
      imageUrl
      clerkId
    }
  }
}
